[package]
name = "dapp_tut"
version = "1.0.0"
authors = []

[addresses]
MyAddress = '0xdc9774757dbc04bd00da146c5f540677b38a02588812e87d8d67e9f869fe7852'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "testnet"
subdir = "aptos-framework"

[dev-dependencies]
